# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ddang/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ddang/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/test/CMakeFiles /home/ddang/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ddang/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named timer

# Build rule for target.
timer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timer
.PHONY : timer

# fast build rule for target.
timer/fast:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/build
.PHONY : timer/fast

src/library/Channel.o: src/library/Channel.cc.o

.PHONY : src/library/Channel.o

# target to build an object file
src/library/Channel.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Channel.cc.o
.PHONY : src/library/Channel.cc.o

src/library/Channel.i: src/library/Channel.cc.i

.PHONY : src/library/Channel.i

# target to preprocess a source file
src/library/Channel.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Channel.cc.i
.PHONY : src/library/Channel.cc.i

src/library/Channel.s: src/library/Channel.cc.s

.PHONY : src/library/Channel.s

# target to generate assembly for a file
src/library/Channel.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Channel.cc.s
.PHONY : src/library/Channel.cc.s

src/library/EPoller.o: src/library/EPoller.cc.o

.PHONY : src/library/EPoller.o

# target to build an object file
src/library/EPoller.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EPoller.cc.o
.PHONY : src/library/EPoller.cc.o

src/library/EPoller.i: src/library/EPoller.cc.i

.PHONY : src/library/EPoller.i

# target to preprocess a source file
src/library/EPoller.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EPoller.cc.i
.PHONY : src/library/EPoller.cc.i

src/library/EPoller.s: src/library/EPoller.cc.s

.PHONY : src/library/EPoller.s

# target to generate assembly for a file
src/library/EPoller.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EPoller.cc.s
.PHONY : src/library/EPoller.cc.s

src/library/EventLoop.o: src/library/EventLoop.cc.o

.PHONY : src/library/EventLoop.o

# target to build an object file
src/library/EventLoop.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoop.cc.o
.PHONY : src/library/EventLoop.cc.o

src/library/EventLoop.i: src/library/EventLoop.cc.i

.PHONY : src/library/EventLoop.i

# target to preprocess a source file
src/library/EventLoop.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoop.cc.i
.PHONY : src/library/EventLoop.cc.i

src/library/EventLoop.s: src/library/EventLoop.cc.s

.PHONY : src/library/EventLoop.s

# target to generate assembly for a file
src/library/EventLoop.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoop.cc.s
.PHONY : src/library/EventLoop.cc.s

src/library/EventLoopThread.o: src/library/EventLoopThread.cc.o

.PHONY : src/library/EventLoopThread.o

# target to build an object file
src/library/EventLoopThread.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoopThread.cc.o
.PHONY : src/library/EventLoopThread.cc.o

src/library/EventLoopThread.i: src/library/EventLoopThread.cc.i

.PHONY : src/library/EventLoopThread.i

# target to preprocess a source file
src/library/EventLoopThread.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoopThread.cc.i
.PHONY : src/library/EventLoopThread.cc.i

src/library/EventLoopThread.s: src/library/EventLoopThread.cc.s

.PHONY : src/library/EventLoopThread.s

# target to generate assembly for a file
src/library/EventLoopThread.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/EventLoopThread.cc.s
.PHONY : src/library/EventLoopThread.cc.s

src/library/Logger.o: src/library/Logger.c.o

.PHONY : src/library/Logger.o

# target to build an object file
src/library/Logger.c.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Logger.c.o
.PHONY : src/library/Logger.c.o

src/library/Logger.i: src/library/Logger.c.i

.PHONY : src/library/Logger.i

# target to preprocess a source file
src/library/Logger.c.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Logger.c.i
.PHONY : src/library/Logger.c.i

src/library/Logger.s: src/library/Logger.c.s

.PHONY : src/library/Logger.s

# target to generate assembly for a file
src/library/Logger.c.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/Logger.c.s
.PHONY : src/library/Logger.c.s

src/library/ThreadPool.o: src/library/ThreadPool.cc.o

.PHONY : src/library/ThreadPool.o

# target to build an object file
src/library/ThreadPool.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/ThreadPool.cc.o
.PHONY : src/library/ThreadPool.cc.o

src/library/ThreadPool.i: src/library/ThreadPool.cc.i

.PHONY : src/library/ThreadPool.i

# target to preprocess a source file
src/library/ThreadPool.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/ThreadPool.cc.i
.PHONY : src/library/ThreadPool.cc.i

src/library/ThreadPool.s: src/library/ThreadPool.cc.s

.PHONY : src/library/ThreadPool.s

# target to generate assembly for a file
src/library/ThreadPool.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/ThreadPool.cc.s
.PHONY : src/library/ThreadPool.cc.s

src/library/TimerQueue.o: src/library/TimerQueue.cc.o

.PHONY : src/library/TimerQueue.o

# target to build an object file
src/library/TimerQueue.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/TimerQueue.cc.o
.PHONY : src/library/TimerQueue.cc.o

src/library/TimerQueue.i: src/library/TimerQueue.cc.i

.PHONY : src/library/TimerQueue.i

# target to preprocess a source file
src/library/TimerQueue.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/TimerQueue.cc.i
.PHONY : src/library/TimerQueue.cc.i

src/library/TimerQueue.s: src/library/TimerQueue.cc.s

.PHONY : src/library/TimerQueue.s

# target to generate assembly for a file
src/library/TimerQueue.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/src/library/TimerQueue.cc.s
.PHONY : src/library/TimerQueue.cc.s

timer.o: timer.cc.o

.PHONY : timer.o

# target to build an object file
timer.cc.o:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/timer.cc.o
.PHONY : timer.cc.o

timer.i: timer.cc.i

.PHONY : timer.i

# target to preprocess a source file
timer.cc.i:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/timer.cc.i
.PHONY : timer.cc.i

timer.s: timer.cc.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cc.s:
	$(MAKE) -f CMakeFiles/timer.dir/build.make CMakeFiles/timer.dir/timer.cc.s
.PHONY : timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... timer"
	@echo "... edit_cache"
	@echo "... src/library/Channel.o"
	@echo "... src/library/Channel.i"
	@echo "... src/library/Channel.s"
	@echo "... src/library/EPoller.o"
	@echo "... src/library/EPoller.i"
	@echo "... src/library/EPoller.s"
	@echo "... src/library/EventLoop.o"
	@echo "... src/library/EventLoop.i"
	@echo "... src/library/EventLoop.s"
	@echo "... src/library/EventLoopThread.o"
	@echo "... src/library/EventLoopThread.i"
	@echo "... src/library/EventLoopThread.s"
	@echo "... src/library/Logger.o"
	@echo "... src/library/Logger.i"
	@echo "... src/library/Logger.s"
	@echo "... src/library/ThreadPool.o"
	@echo "... src/library/ThreadPool.i"
	@echo "... src/library/ThreadPool.s"
	@echo "... src/library/TimerQueue.o"
	@echo "... src/library/TimerQueue.i"
	@echo "... src/library/TimerQueue.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

